source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Mitter SDK Demo' do
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod ‘Mitter’, :path => ‘../Mitter’
end
