source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Mitter SDK Demo' do
    pod 'Alamofire', '~> 4.7'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'Moya/RxSwift', '~> 11.0'
    pod 'Moya-ModelMapper/RxSwift', '7.1.0'
    pod 'PhoneNumberKit', '~> 2.5'
    pod 'Swinject', '~> 2.5.0'
    pod 'JWTDecode', '~> 2.1'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Unbox'
end
